// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DrugPrevention.Repositories.NganVHH.Models;

[Table("CommunityProgramsToanNS")]
[Index("Status", Name = "IDX_CommunityProgramsToanNS_Status")]
public partial class CommunityProgramsToanN
{
    [Key]
    public int ProgramToanNSID { get; set; }

    [Required]
    [StringLength(100)]
    public string ProgramName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    [StringLength(255)]
    public string Location { get; set; }

    public int? MaxParticipants { get; set; }

    public int? CurrentParticipants { get; set; }

    [Required]
    [StringLength(20)]
    public string Status { get; set; }

    public int? OrganizerId { get; set; }

    public bool? IsActive { get; set; }

    [ForeignKey("OrganizerId")]
    [InverseProperty("CommunityProgramsToanNs")]
    public virtual UsersTuyenTM Organizer { get; set; }

    [InverseProperty("ProgramToanNS")]
    public virtual ICollection<ProgramParticipantsToanN> ProgramParticipantsToanNs { get; set; } = new List<ProgramParticipantsToanN>();
}