// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DrugPrevention.Repositories.NganVHH.Models;

[Table("ConsultantsTrongLH")]
[Index("IsAvailable", Name = "IDX_ConsultantsTrongLH_IsAvailable")]
[Index("Specialization", Name = "IDX_ConsultantsTrongLH_Specialization")]
[Index("UserID", Name = "IDX_ConsultantsTrongLH_UserID")]
public partial class ConsultantsTrongLH
{
    [Key]
    public int ConsultantTrongLHID { get; set; }

    /// <summary>
    /// Liên kết đến bảng UsersTuyenTM để xác định tài khoản user của chuyên gia tư vấn
    /// </summary>
    public int UserID { get; set; }

    [Required]
    [StringLength(100)]
    public string Specialization { get; set; }

    [StringLength(255)]
    public string Qualification { get; set; }

    [StringLength(255)]
    public string Certification { get; set; }

    public int? YearsOfExperience { get; set; }

    [Column(TypeName = "decimal(3, 2)")]
    public decimal? AverageRating { get; set; }

    public int? TotalConsultations { get; set; }

    public bool? IsAvailable { get; set; }

    public bool? ProfileVerified { get; set; }

    [InverseProperty("Consultant")]
    public virtual ICollection<AppointmentsNganVHH> AppointmentsNganVHHs { get; set; } = new List<AppointmentsNganVHH>();

    [InverseProperty("Consultant")]
    public virtual ICollection<ConsultantScheduleTrongLH> ConsultantScheduleTrongLHs { get; set; } = new List<ConsultantScheduleTrongLH>();

    [ForeignKey("UserID")]
    [InverseProperty("ConsultantsTrongLHs")]
    public virtual UsersTuyenTM User { get; set; }
}