// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DrugPrevention.Repositories.NganVHH.Models;

[Table("ConsultantScheduleTrongLH")]
[Index("ConsultantID", "DayOfWeek", "StartTime", "EndTime", "EffectiveFrom", Name = "UC_ConsultantSchedule", IsUnique = true)]
public partial class ConsultantScheduleTrongLH
{
    [Key]
    public int ScheduleTrongLHID { get; set; }

    public int ConsultantID { get; set; }

    public int DayOfWeek { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public bool? IsAvailable { get; set; }

    [StringLength(50)]
    public string RecurringPattern { get; set; }

    public DateOnly EffectiveFrom { get; set; }

    public DateOnly? EffectiveTo { get; set; }

    public int? MaxAppointmentsPerSlot { get; set; }

    public int? BufferMinutesBetweenMeetings { get; set; }

    [Column(TypeName = "ntext")]
    public string Notes { get; set; }

    [ForeignKey("ConsultantID")]
    [InverseProperty("ConsultantScheduleTrongLHs")]
    public virtual ConsultantsTrongLH Consultant { get; set; }
}