// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DrugPrevention.Repositories.NganVHH.Models;

[Table("CoursesQuangTNV")]
[Index("AgeGroup", Name = "IDX_CoursesQuangTNV_AgeGroup")]
[Index("Category", Name = "IDX_CoursesQuangTNV_Category")]
[Index("IsActive", Name = "IDX_CoursesQuangTNV_IsActive")]
public partial class CoursesQuangTNV
{
    [Key]
    public int CourseQuangTNVID { get; set; }

    [Required]
    [StringLength(100)]
    public string Title { get; set; }

    [Required]
    [StringLength(50)]
    public string AgeGroup { get; set; }

    [Required]
    [StringLength(50)]
    public string Category { get; set; }

    public int DurationInMinutes { get; set; }

    [StringLength(100)]
    public string InstructorName { get; set; }

    [StringLength(255)]
    public string ContentURL { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "decimal(3, 2)")]
    public decimal? Rating { get; set; }

    [InverseProperty("Course")]
    public virtual ICollection<UserCoursesTuyenTM> UserCoursesTuyenTMs { get; set; } = new List<UserCoursesTuyenTM>();
}