// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DrugPrevention.Repositories.NganVHH.Models;

[Table("ProgramParticipantsToanNS")]
public partial class ProgramParticipantsToanN
{
    [Key]
    public int ParticipantToanNSID { get; set; }

    public int ProgramToanNSID { get; set; }

    public int UserID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RegistrationDate { get; set; }

    [StringLength(20)]
    public string AttendanceStatus { get; set; }

    public bool? FeedbackProvided { get; set; }

    public int? FeedbackRating { get; set; }

    public bool? CertificateIssued { get; set; }

    [StringLength(50)]
    public string ParticipantRole { get; set; }

    [Column(TypeName = "ntext")]
    public string FeedbackComments { get; set; }

    [ForeignKey("ProgramToanNSID")]
    [InverseProperty("ProgramParticipantsToanNs")]
    public virtual CommunityProgramsToanN ProgramToanNS { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("ProgramParticipantsToanNs")]
    public virtual UsersTuyenTM User { get; set; }
}