// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DrugPrevention.Repositories.NganVHH.Models;

[Table("SurveyQuestionsQuangTNV")]
public partial class SurveyQuestionsQuangTNV
{
    [Key]
    public int QuestionQuangTNVID { get; set; }

    public int SurveyID { get; set; }

    [Required]
    [Column(TypeName = "ntext")]
    public string QuestionText { get; set; }

    [Required]
    [StringLength(50)]
    public string QuestionType { get; set; }

    [Column(TypeName = "ntext")]
    public string Options { get; set; }

    public bool? IsRequired { get; set; }

    public int QuestionOrder { get; set; }

    public int? RiskWeight { get; set; }

    [Column(TypeName = "ntext")]
    public string HelpText { get; set; }

    public int? DependsOnQuestionID { get; set; }

    [StringLength(255)]
    public string DependsOnAnswer { get; set; }

    [StringLength(255)]
    public string ImageURL { get; set; }

    [ForeignKey("SurveyID")]
    [InverseProperty("SurveyQuestionsQuangTNVs")]
    public virtual SurveysNamND Survey { get; set; }
}