// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DrugPrevention.Repositories.NganVHH.Models;

[Table("SurveysNamND")]
[Index("IsActive", Name = "IDX_SurveysNamND_IsActive")]
public partial class SurveysNamND
{
    [Key]
    public int SurveyNamNDID { get; set; }

    [Required]
    [StringLength(100)]
    public string SurveyName { get; set; }

    [Required]
    [StringLength(50)]
    public string SurveyType { get; set; }

    public int TotalQuestions { get; set; }

    public int? MaxRiskScore { get; set; }

    [StringLength(50)]
    public string TargetAudience { get; set; }

    public bool IsActive { get; set; }

    public bool? IsAnonymous { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    public int? Creator { get; set; }

    [InverseProperty("Survey")]
    public virtual ICollection<SurveyQuestionsQuangTNV> SurveyQuestionsQuangTNVs { get; set; } = new List<SurveyQuestionsQuangTNV>();

    [InverseProperty("Survey")]
    public virtual ICollection<UserSurveysNamND> UserSurveysNamNDs { get; set; } = new List<UserSurveysNamND>();
}