// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DrugPrevention.Repositories.NganVHH.Models;

[Table("UserSurveysNamND")]
public partial class UserSurveysNamND
{
    [Key]
    public int UserSurveyNamNDID { get; set; }

    public int? UserID { get; set; }

    public int SurveyID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SubmissionDate { get; set; }

    public int? RiskScore { get; set; }

    [Column(TypeName = "ntext")]
    public string Recommendations { get; set; }

    public int? CompletionTime { get; set; }

    public bool? IsAnonymous { get; set; }

    [Column(TypeName = "ntext")]
    public string ResultSummary { get; set; }

    [ForeignKey("SurveyID")]
    [InverseProperty("UserSurveysNamNDs")]
    public virtual SurveysNamND Survey { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("UserSurveysNamNDs")]
    public virtual UsersTuyenTM User { get; set; }
}