// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DrugPrevention.Repositories.NganVHH.Models;

[Table("UsersTuyenTM")]
[Index("IsActive", Name = "IDX_UsersTuyenTM_IsActive")]
[Index("Role", Name = "IDX_UsersTuyenTM_Role")]
[Index("Username", Name = "UQ__UsersTuy__536C85E456529E7A", IsUnique = true)]
[Index("Email", Name = "UQ__UsersTuy__A9D1053480A4EFCF", IsUnique = true)]
public partial class UsersTuyenTM
{
    [Key]
    public int UserTuyenTMID { get; set; }

    [Required]
    [StringLength(50)]
    public string Username { get; set; }

    [Required]
    [StringLength(255)]
    public string Password { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; }

    [StringLength(50)]
    public string LastName { get; set; }

    [Required]
    [StringLength(20)]
    public string Role { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RegistrationDate { get; set; }

    public bool IsActive { get; set; }

    [StringLength(20)]
    public string PhoneNumber { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<AppointmentsNganVHH> AppointmentsNganVHHs { get; set; } = new List<AppointmentsNganVHH>();

    [InverseProperty("Organizer")]
    public virtual ICollection<CommunityProgramsToanN> CommunityProgramsToanNs { get; set; } = new List<CommunityProgramsToanN>();

    [InverseProperty("User")]
    public virtual ICollection<ConsultantsTrongLH> ConsultantsTrongLHs { get; set; } = new List<ConsultantsTrongLH>();

    [InverseProperty("User")]
    public virtual ICollection<ProgramParticipantsToanN> ProgramParticipantsToanNs { get; set; } = new List<ProgramParticipantsToanN>();

    [InverseProperty("User")]
    public virtual ICollection<UserCoursesTuyenTM> UserCoursesTuyenTMs { get; set; } = new List<UserCoursesTuyenTM>();

    [InverseProperty("User")]
    public virtual ICollection<UserSurveysNamND> UserSurveysNamNDs { get; set; } = new List<UserSurveysNamND>();
}